[package]
name = "grepox"
version = "0.2.10"
description = "Minimalist's grep written in Rust."
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/Vonr/grepox"
repository = "https://github.com/Vonr/grepox"
keywords = ["grep", "search", "cli", "fast", "minimal"]
edition = "2021"

[dependencies]
regex = "1.5.5"
atty = "0.2.14"
naive_opt = "0.1.17"
